### ISSUE TITLE
Extra email common headers 

### ISSUE THREAD

**Issue by cturbelin** [influenzanet/messaging-service#1]
We will need some extra fields to be able to do bounce management :

- Sender
- Reply-To

The common scenario is to define From and Sender to a bounce box and Reply-To to the team contact box to receive all the bounces replies in a separated box.. In this case the From field is always set by the server config.

In our platform we finally remove the ability to set by message or template the From address, because it can be dangerous : some message was sent using a typo in the domain (they were set in a template) and our server were flagged as spam during several weeks.

**Comment by phev8** [comment]
Sender and ReplyTo should be one global setting for all types of emails, or rather configured by message type? (there are types for account emails, like verifying email address, then newsletter like...)

**Comment by cturbelin** [comment]
I think they should be global by default...A given platform will probably have one bounce management map, regardless the email type (is handled during the bounce processing) so you only need one bounce address.
The reply-to can be the requested "From", and the From & Sender becomes the target address for bounces (and auto-reply).

Currently all our platform only use one From address for all emails (contact@[domain]), I dont know if we need more ?

I dont know what are the use cases for emails reply : in which case we can accept a reply from a user or not.. Maybe in an automatic email it's not a good idea (if you reply with the content of the email, with a token to change your password you reveal it to the target account)..but people transfer those email to our team.

**Comment by phev8** [comment]
Ok for the backend, I would propose, that we can then set:
From
Sender
ReplyTo
as one global default. Additionally, the backend would support overrides for all of these per message type, but first the UI don't have to offer the possibility. At least, later if there is a use case, we don't have to modify the interface too much. 

Yes, I don't think, we can prevent people forwarding their emails, even if it's not advised. On the other hand, the url link is only valid once for the new platform and expires after a while, so not that bad as for the old one.

**Comment by phev8** [comment]
Do you have any other need for setting custom header-fields?

**Comment by cturbelin** [comment]
Yes, thank you !
Yes we can imagine sometimes we would need to send message with a different from, but for instance I dont think it would be need for the UI (maybe it's more a service : some can send with another from the it's configured in the service).. 

Maybe another thing could be to check the domain of the from (we can imagine we will have a reduced list of domains in use for a platform (most probably only one) and an email should not be sent with another domain no ? (for security and also prevent spam problem, it can reduce risk if someone enter a bad sender email)

For the other headers, we considered to add some extra header to define some metadata in the email (to be able to flag them in the bounce handler, like "X-Ifn-Action:", because it's not easy to know what is the kind of message that trigger the bounce (we have the original message but it's not easy). But it's not a must-have feature of course, just a vague project.

We use DKIM signature, but it's done on the smtp server side.

**Comment by phev8** [comment]
With version v0.3.0, setting "sender", "replyTo" (list of addresses) and "from" address is possible, via the config yaml file. 
Also included an option to try to connect to servers without auth (leave user and password fields empty)
